const express = require('express')
const app = express()
const router = require('./router')
const { JSDOM } = require("jsdom")
const axios = require('axios')
app.use(express.urlencoded({extended: false}))
app.use(express.json())

app.use('/', router)
app.listen(3000)